export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const SIGNOUT = 'SIGNOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAILED = 'CREATE_PROFILE_FAILED';
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
// export const ADD_EXPERIENCE_FAILED = 'ADD_EXPERIENCE_FAILED';
export const REMOVE_EXPERIENCE_SUCCESS = 'REMOVE_EXPERIENCE_SUCCESS';
// export const REMOVE_EXPERIENCE_FAILED = 'REMOVE_EXPERIENCE_FAILED';
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';
export const REMOVE_EDUCATION_SUCCESS = 'REMOVE_EDUCATION_SUCCESS';

export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS';
export const GET_PROFILE_DETAIL = 'GET_PROFILE_DETAIL';
export const GET_PROFILE_REPOS = 'GET_PROFILE_REPOS';
export const CLEAR_PROFILE_DETAIL = 'CLEAR_PROFILE_DETAIL';

